= Magic Kit

Neovim starter kit for working with https://github.com/Olical/conjure[Conjure] and https://github.com/Olical/aniseed[Aniseed], contains everything you need to get started. The goal is for you to take this and modify it to fit your needs, it is _not_ a distribution I'll constantly tweak, it's a starting point you should change as you see fit.

== Requirements

 * git (for cloning the project and managing plugins)
 * Neovim 0.5+ (this is unreleased at the time of writing, you'll have to find a nightly build or compile it yourself)

== Installation

[source,bash]
----
# Clone the project into your Neovim configuration directory.
# Make sure you don't have anything here already! Back it up if so!
git clone git@github.com:Olical/magic-kit.git ~/.config/nvim

# Perform the initial sync which will fetch all of the plugins.
# Run then whenever you change the plugin configuration.
~/.config/nvim/script/sync.sh
----

Once done, have a look at `~/.config/nvim/init.lua` to learn about the bootstrap process then `~/.config/nvim/fnl/magic/init.fnl` for the real beginning of your Fennel based configuration. Good luck! Have fun!

== Mappings

If you press a key and then wait, https://github.com/folke/which-key.nvim[which-key] will pop up with suggestions of what you can press next. Here's a few key mappings defined in the configuration to get you started.

 * `<space>` is the https://learnvimscriptthehardway.stevelosh.com/chapters/06.html#leader[leader key] (`<leader>`)
 * `,` is the https://learnvimscriptthehardway.stevelosh.com/chapters/06.html#local-leader[local leader key] (`<localleader>`)
 * `<leader>f...` finds things with https://github.com/nvim-telescope/telescope.nvim[telescope]
 ** Try `<leader>ff` to find files and `<leader>fb` to find buffers, there's a bunch of mappings so you'll have to experiment and rely on which-key
 * `<leader>ut` opens https://github.com/mbbill/undotree[undotree]

== Unlicenced

> You can change this in your own repository, I don't care! Do what you want with this repository, attribution is appreciated but not required.

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____
